# 配置端口
server:
  port: 8080
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: mainyi
  #配置开发环境
  profiles:
    active: dev
#  mvc:
#    static-path-pattern: static/**
  resources:
    static-locations: classpath:/static/,classpath:/templates/
#  #声明thymeleaf使用非严格的html。
#  thymeleaf:
#    content-type: text/html
#    mode: LEGACYHTML5
#    cache: false
# mybatis-plus相关配置
mybatis-plus:
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      #      id-type: auto
      #      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #      #数据库类型
      db-type: MYSQL
  configuration:
    #    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
